[package]
name = "refineid-rapp-core"
description = "Remote Authorization Proxy Protocol (RAPP) requester core for Windows"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
getrandom.workspace = true
sha2.workspace = true
snow = "0.10"
zeroize.workspace = true

[dev-dependencies]

[lints]
workspace = true
